### ISSUE TITLE
查找端口占用显示信息不全

### ISSUE THREAD

**Issue by maxyou2090** [nicejade/arya-jarvis-doc#1]
mac系统，使用：arya port 80 显示信息不全

手动执行：sudo lsof -i tcp:80 则显示正常，占用80端口的是nginx服务，应该是需要root权限才能查看，能不能默认加上root权限呢

**Comment by nicejade** [comment]
@yorkfread 嗯，可以的，会尽快加上；感谢反馈。

**Comment by nicejade** [comment]
@yorkfread 已经在 https://github.com/nicejade/arya-jarvis/commit/0738c05e59cb2f3ab172db7724870ad2037c27d4 这笔提交中为 `lsof` 加上 `sudo`，并在 [1.9.2](https://www.npmjs.com/package/arya-jarvis) 中发布。
